name: mow
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  mow:
    runs-on: ubuntu-latest
    steps:
      - uses: sudongcu/mowmow@v1
        with:
          github_user_name: sudongcu
          cycle: "57"
          mower: goat
          outputs: |
            lawn.svg?stripes=false
            lawn-dark.svg?stripes=false&theme=dark
