name: mow
on:
  schedule:
    - cron: "30 15 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  mow:
    runs-on: ubuntu-latest
    steps:
      - uses: sudongcu/mowmow@v1
        with:
          github_user_name: sudongcu
          github_token: ${{ secrets.MOWMOW_TOKEN }}
          cycle: "54"
          mower: goat
          mower_color: "#d9964a"
