name: mow
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
permissions:
  contents: write
jobs:
  mow:
    runs-on: ubuntu-latest
    steps:
      - uses: sudongcu/mowmow@main
        with:
          github_user_name: sudongcu
          cycle: "54"
          mower: goat
          mower_color: "#d9964a"
